// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class T1Test
{
    private IWebDriver _driver;
    public IWebDriver driver
    {
        get
        {
            Thread.Sleep(500);
            return _driver;
        }

        set
        { _driver = value; }
    }
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void t1()
    {
        driver.Navigate().GoToUrl("https://demos.devexpress.com/MVCxGridViewDemos/Filtering/Filtering");
        driver.Manage().Window.Size = new System.Drawing.Size(1280, 768);
        driver.Manage().Timeouts().ImplicitWait=new TimeSpan(3000);

        driver.FindElement(By.CssSelector("#gvFiltering_col1 .dxGridView_gvHeaderFilter_MaterialCompact")).Click();
        driver.FindElement(By.Id("gvFiltering_HFListBox1_!Argentina_D")).Click();
        js.ExecuteScript("window.scrollTo(0,0)");
        js.ExecuteScript("window.scrollTo(0,0)");
        {
            var element = driver.FindElement(By.Id("gvFiltering_HFListBox1_D"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.Id("gvFiltering_HFListBox1_D"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.Id("gvFiltering_HFListBox1_D"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
     //   driver.FindElement(By.Id("gvFiltering_HFListBox1_!Venezuela_D")).Click();
        driver.FindElement(By.CssSelector("#gvFiltering_DXHFP_O_CD > .dx-vam")).Click();
        js.ExecuteScript("window.scrollTo(0,0)");
        driver.FindElement(By.CssSelector("#gvFiltering_col3 .dxGridView_gvHeaderFilter_MaterialCompact")).Click();
        driver.FindElement(By.Id("gvFiltering_HFListBox3_!2.5000_D")).Click();
        driver.FindElement(By.CssSelector("#gvFiltering_DXHFP_TPCFCm1_O_CD > .dx-vam")).Click();
        js.ExecuteScript("window.scrollTo(0,0)");
        driver.Close();
    }
}
